name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Verify Ulam 164
        uses: leanprover/lean-action@v1
        with:
          lake-package-directory: "PaperFormalization/Ulam 164"

      - name: Verify Ulam 165
        uses: leanprover/lean-action@v1
        with:
          lake-package-directory: "PaperFormalization/Ulam 165"